### ISSUE TITLE
210417~210423

### ISSUE THREAD

**Issue by jig6795** [SSAFY-Algo/Algorithm#124]

**Comment by jig6795** [comment]
[SWEA 격자판의 숫자 이어 붙이기](https://swexpertacademy.com/main/code/problem/problemDetail.do?problemLevel=4&contestProbId=AV7I5fgqEogDFAXB&categoryId=AV7I5fgqEogDFAXB&categoryType=CODE&problemTitle=&orderBy=SUBMIT_COUNT&selectCodeLang=ALL&select-1=4&pageSize=10&pageIndex=1)

**Comment by sewonkimm** [comment]
[BOJ 17086 아기상어2](https://www.acmicpc.net/problem/17086)

**Comment by ShinDajeong** [comment]
[SWEA 차량 정비소](https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV6c6bgaIuoDFAXy)

**Comment by ingorithm** [comment]
[BOJ AC](https://www.acmicpc.net/problem/5430)

**Comment by jihoneyy** [comment]
[POG 순위](https://programmers.co.kr/learn/courses/30/lessons/49191)
