### ISSUE TITLE
210507~210514

### ISSUE THREAD

**Issue by ingorithm** [SSAFY-Algo/Algorithm#132]
- 5월 14일 오후 9시 스터디
- 맨 첫번째 올린 문제 5월 14일에 같이 풀어요!
- 미리 풀기 금지!!
- 풀이 시간은 30분 정도 걸리는 문제로~

**Comment by ingorithm** [comment]
[BOJ 괄호의 값](https://www.acmicpc.net/problem/2504)
- 미리 풀지 마세요~

**Comment by jig6795** [comment]
[BOJ 나무 자르기](https://www.acmicpc.net/problem/2805)
늦게 올려서 죄송합니당🤯

**Comment by jihoneyy** [comment]
[BOJ 친구](https://www.acmicpc.net/problem/1058)

**Comment by sewonkimm** [comment]
[BOJ 요세푸스문제](https://www.acmicpc.net/problem/1158)

늦어서 미안합니다... 오늘부터 갓생산다...

**Comment by ShinDajeong** [comment]
[BOJ 장난감조립](https://www.acmicpc.net/problem/2637)
