### ISSUE TITLE
201217~201224 문제목록

### ISSUE THREAD

**Issue by sewonkimm** [SSAFY-Algo/Algorithm#28]

**Comment by rhdrlvnd** [comment]
[BOJ 문제집](https://www.acmicpc.net/problem/1766)

**Comment by ShinDajeong** [comment]
[BOJ 01타일](https://www.acmicpc.net/problem/1904)

**Comment by ingorithm** [comment]
[BOJ 사탕](https://www.acmicpc.net/problem/1415)

**Comment by jihoneyy** [comment]
[BOJ 별자리 만들기](https://www.acmicpc.net/problem/4386)

**Comment by sewonkimm** [comment]
[BOJ 낚시왕](https://www.acmicpc.net/problem/17143) - 삼성기출

**Comment by jig6795** [comment]
[BOJ 빗물](https://www.acmicpc.net/problem/14719)

**Comment by yyoooona** [comment]
[BOJ 양치기 꿍] (https://www.acmicpc.net/problem/3187)

**Comment by yyoooona** [comment]
[BOJ 양치기 꿍](https://www.acmicpc.net/problem/3187)
