### ISSUE TITLE
210205 ~ 210219

### ISSUE THREAD

**Issue by sewonkimm** [SSAFY-Algo/Algorithm#79]
세원 인구 지헌 다정

**Comment by ingorithm** [comment]
[PROG 카펫](https://programmers.co.kr/learn/courses/30/lessons/42842)

**Comment by sewonkimm** [comment]
[SWEA 백만장자프로젝트](https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV5LrsUaDxcDFAXc&categoryId=AV5LrsUaDxcDFAXc&categoryType=CODE&problemTitle=&orderBy=RECOMMEND_COUNT&selectCodeLang=ALL&select-1=&pageSize=10&pageIndex=1#)

**Comment by ShinDajeong** [comment]
[PROG 디스크 컨트롤러](https://programmers.co.kr/learn/courses/30/lessons/42627)

**Comment by jihoneyy** [comment]
[나이트의 이동](https://www.acmicpc.net/problem/7562)
